let urunler = [
  {
    id: 1,
    marka: "Ege",
    fiyat: 2790,
    malzemeturu: "Tyana Klozet + Rezervuar Extra 1.Kalite",
    resim: "Urunler/ege-tyana-klozet.jpeg",
    tur: "klozet",
  },
  {
    id: 2,
    marka: "Ege",
    fiyat: 2650,
    malzemeturu: "Lagina Klozet + Rezervuar Extra 1.Kalite",
    resim: "Urunler/ege-lagina-klozet.jpeg",
    tur: "klozet",
  },
  {
    id: 3,
    marka: "Ege",
    fiyat: 2400,
    malzemeturu: "Likya Klozet + Rezervuar Extra",
    resim: "Urunler/ege-likya-klozet.jpeg",
    tur: "klozet",
  },
  {
    id: 4,
    marka: "Ege",
    fiyat: 1350,
    malzemeturu: "Era Alttan Çıkışlı Klozet + Rezervuar",
    resim: "Urunler/ege-eraalttan-klozet.jpeg",
    tur: "klozet",
  },
  {
    id: 5,
    marka: "Ege",
    fiyat: 1490,
    malzemeturu: "Kapya Arkadan Çıkışlı Klozet + Rezervuar",
    resim: "Urunler/ege-kapyaarkadan-klozet.jpeg",
    tur: "klozet",
  },
  {
    id: 6,
    marka: "Ege",
    fiyat: 750,
    malzemeturu: "Era İçten Yıkamalı Helataşı",
    resim: "Urunler/ege-era-helatasi.jpeg",
    tur: "",
  },
  {
    id: 7,
    marka: "Ege",
    fiyat: 430,
    malzemeturu: "Likya Büyük Yarım Ayak",
    resim: "Urunler/ege-likya-buyukyarimayak.jpeg",
    tur: "lavabo",
  },
  {
    id: 8,
    marka: "Ege",
    fiyat: 740,
    malzemeturu: "Ege Trenda 56 CM Lavabo",
    resim: "Urunler/ege-trenda-56cmlavabo.jpeg",
    tur: "lavabo",
  },
  {
    id: 9,
    marka: "Ege",
    fiyat: 355,
    malzemeturu: "28*35 Lissa Lavabo",
    resim: "Urunler/ege-lissa-2835lavabo.jpeg",
    tur: "lavabo",
  },
  {
    id: 10,
    marka: "Ege",
    fiyat: 530,
    malzemeturu: "35*45 Lissa Lavabo",
    resim: "Urunler/ege-lissa-3545lavabo.jpeg",
    tur: "lavabo",
  },
  {
    id: 11,
    marka: "Ege",
    fiyat: 395,
    malzemeturu: "Yarım Ayak",
    resim: "Urunler/ege-yarimayak.jpeg",
    tur: "lavabo",
  },
  {
    id: 12,
    marka: "Ece",
    fiyat: 2390,
    malzemeturu: "Ece Karizma Klozet + Rezervuar Karizma Kutulu",
    resim: "Urunler/ece-karizma-klozet.jpeg",
    tur: "klozet",
  },
  {
    id: 13,
    marka: "Ece",
    fiyat: 1990,
    malzemeturu: "Ece Savoy Klozet + Rezervuar Duvara Sıfır",
    resim: "Urunler/ece-savoy-klozet.jpeg",
    tur: "klozet",
  },
  {
    id: 14,
    marka: "Ece",
    fiyat: 550,
    malzemeturu: "Eti 40*50 Lavabo",
    resim: "Urunler/ece-eti-4050lavabo.jpg",
    tur: "lavabo",
  },
  {
    id: 15,
    marka: "Ece",
    fiyat: 715,
    malzemeturu: "Eti 61 CM Lavabo",
    resim: "Urunler/ece-eti-61lavabo.jpeg",
    tur: "lavabo",
  },
  {
    id: 16,
    marka: "Ece",
    fiyat: 465,
    malzemeturu: "Eti Yarım Ayak",
    resim: "Urunler/ece-eti-yarimayak.jpeg",
    tur: "lavabo",
  },
  {
    id: 17,
    marka: "Ece",
    fiyat: 360,
    malzemeturu: "Ece 28*35 Lavabo Delikli",
    resim: "Urunler/ece-ece-2835lavabodelikli.jpeg",
    tur: "lavabo",
  },
  {
    id: 18,
    marka: "Ece",
    fiyat: 725,
    malzemeturu: "İçten Yıkamalı Helataşı",
    resim: "Urunler/ece-ictenyikamalihelatasi.jpeg",
    tur: "",
  },
  {
    id: 19,
    marka: "Ece",
    fiyat: 1290,
    malzemeturu: "Eti Klozet + Rezervuar",
    resim: "Urunler/ece-eti-klozet.jpeg",
    tur: "klozet",
  },
];
